services:
  unbound:
    image: gibsonsoft/unbound-full
    container_name: unbound
    pull_policy: never
    environment:
      CONTROL_ENABLE: yes
    build:
      context: .
      target: final
      platforms:
        - linux/amd64
        - linux/arm64/v8
        - linux/ppc64le
        # - linux/arm/v6    # need to remove enable-ec_nistp_64_gcc_128 from openssl compile
        # - linux/arm/v7    # need to remove enable-ec_nistp_64_gcc_128 from openssl compile
        #
        # - linux/386       # 1. need to remove enable-ec_nistp_64_gcc_128 from openssl compile
        #                   # 2. need to add -m32 linux-generic32 to openssl compile
        #
        # - linux/riscv64   # remove upx dependency, doesn't yet support riscv
        #
        # - linux/s390x     # 1. remove upx dependency, no stubs available for s390x
        #                   # 2. remove enable-ec_nistp_64_gcc_128 from openssl compile
      args:
        ALPINE_VERSION: 3.20.2
        XX_VERSION: 1.5.0
        
        CORE_BUILD_DEPS: >
          clang
          lld
          llvm
          make
          perl
          file
          upx
          gnupg
          flex
          bison
          pkgconf

        TARGET_BUILD_DEPS: >
          compiler-rt
          llvm-libunwind
          llvm-libunwind-static
          musl-dev
          linux-headers
        
        LDNS_BUILD_DEPS: >
          libtool

        # OPENSSL_BUILD_DEPS: >

        PROTOBUFC_BUILD_DEPS: >
          protobuf-dev
        
        UNBOUND_BUILD_DEPS: >
          expat-dev
          expat-static
          libevent-dev
          libevent-static
          libsodium-dev
          libsodium-static
          nghttp2-dev
          nghttp2-static
          hiredis-dev

        # In order of appearance:
        # OpenSSL OMC
        # Richard Levitte
        # Matt Caswell
        # Paul Dale
        # Tomas Mraz
        OPENSSL_OPGP_KEYS: >
          EFC0A467D613CB83C7ED6D30D894E2CE8B3D79F5
          7953AC1FBC3DC8B3B292393ED5E9E43F7DF9EE8C
          8657ABB260F056B1E5190839D9C4D26D0E604491
          B7C1C14360F353A36862E4D5231C84CDDCC69C45
          A21FAB74B0088AA361152586B8EF1A6BA9DA2D5C

        OPENSSL_SHA256: 777cd596284c883375a2a7a11bf5d2786fc5413255efab20c50d6ffe6d020b7e
        OPENSSL_SOURCE: https://www.openssl.org/source/
        OPENSSL_VERSION: 3.3.1

        PROTOBUFC_SHA256: 7b404c63361ed35b3667aec75cc37b54298d56dd2bcf369de3373212cc06fd98
        PROTOBUFC_SOURCE: https://github.com/protobuf-c/protobuf-c/releases/download/
        PROTOBUFC_VERSION: 1.5.0

        LDNS_SHA256: c3f72dd1036b2907e3a56e6acf9dfb2e551256b3c1bbd9787942deeeb70e7860
        LDNS_SOURCE: https://nlnetlabs.nl/downloads/ldns/
        LDNS_VERSION: 1.8.3

        UNBOUND_SHA256: e7dca7d6b0f81bdfa6fa64ebf1053b5a999a5ae9278a87ef182425067ea14521
        UNBOUND_SOURCE: https://nlnetlabs.nl/downloads/unbound/
        UNBOUND_VERSION: 1.21.0

        ROOT_HINTS: https://www.internic.net/domain/named.root
        ICANN_CERT: https://data.iana.org/root-anchors/icannbundle.pem
