services:
  unbound:
    image: gibsonsoft/unbound-full
    container_name: unbound
    pull_policy: never
    environment:
      CONTROL_ENABLE: yes
    build:
      context: .
      target: final
      platforms:
        - linux/amd64
        - linux/arm64/v8
        - linux/ppc64le
        # - linux/arm/v6    # need to remove enable-ec_nistp_64_gcc_128 from openssl compile
        # - linux/arm/v7    # need to remove enable-ec_nistp_64_gcc_128 from openssl compile
        #
        # - linux/386       # 1. need to remove enable-ec_nistp_64_gcc_128 from openssl compile
        #                   # 2. need to add -m32 linux-generic32 to openssl compile
        #
        # - linux/riscv64   # remove upx dependency, doesn't yet support riscv
        #
        # - linux/s390x     # 1. remove upx dependency, no stubs available for s390x
        #                   # 2. remove enable-ec_nistp_64_gcc_128 from openssl compile
      args:
        ALPINE_VERSION: 3.20.2
        XX_VERSION: 1.5.0

        BUILD_THREADS: 32
        
        CORE_BUILD_DEPS: >
          clang
          lld
          make
          cmake
          git
          perl
          file
          upx
          gnupg
          flex
          bison
          pkgconf
          automake
          autoconf
          libtool

        TARGET_BUILD_DEPS: >
          g++
          llvm
          compiler-rt
          llvm-libunwind
          llvm-libunwind-static
          musl-dev
          linux-headers
        
        LDNS_BUILD_DEPS: >
          libtool

        PROTOBUF_BUILD_DEPS_BUILD: >
          zlib-dev
          zlib-static

        PROTOBUF_BUILD_DEPS_HOST: >
          zlib-dev
          zlib-static
        
        UNBOUND_BUILD_DEPS: >
          expat-dev
          expat-static
          libevent-dev
          libevent-static
          libsodium-dev
          libsodium-static
          nghttp2-dev
          nghttp2-static
          hiredis-dev

        OPENSSL_GIT_COMMIT: fb7fab9fa6f4869eaa8fbb97e0d593159f03ffe4
        OPENSSL_SOURCE: https://github.com/openssl/openssl.git
        OPENSSL_VERSION: 3.3.2

        PROTOBUF_GIT_COMMIT: 439c42c735ae1efed57ab7771986f2a3c0b99319
        PROTOBUF_SOURCE: https://github.com/protocolbuffers/protobuf.git
        PROTOBUF_VERSION: 28.0

        PROTOBUFC_GIT_COMMIT: 86a89d1e758557e5df60cf47ed98df837ed93428
        PROTOBUFC_SOURCE: https://github.com/protobuf-c/protobuf-c.git
        PROTOBUFC_VERSION: 1.5.0

        LDNS_SHA256: c3f72dd1036b2907e3a56e6acf9dfb2e551256b3c1bbd9787942deeeb70e7860
        LDNS_SOURCE: https://nlnetlabs.nl/downloads/ldns/
        LDNS_VERSION: 1.8.3

        UNBOUND_GIT_COMMIT: 79e4c578518886a32475cfbb0de383ff3a905033
        UNBOUND_SOURCE: https://github.com/NLnetLabs/unbound.git
        UNBOUND_VERSION: 1.21.0

        ROOT_HINTS: https://www.internic.net/domain/named.root
        ICANN_CERT: https://data.iana.org/root-anchors/icannbundle.pem
